# themes.py — ข้อมูลธีมสีทั้งหมดของโปรเจค
# เพิ่มธีมใหม่ได้โดยเพิ่ม key ใหม่ใน THEMES dict

THEMES = {
    "dark": {
        "name":         "Dark",
        "icon":         "🌑",
        "bg":           "#141414",
        "accent":       "#323232",
        "text":         "#FFFFFF",
        "subtext":      "#888888",
        "gold":         "#FFD700",
        "price":        "#C8C8FF",
        "divider":      "#646464",
        "back_bar":     "#1a1a1a",
        "back_divider": "#2a2a2a",
        "up":           "#00FF64",
        "down":         "#FF5050",
        "entry_fg":     "#FFFFFF",
    },
    "light": {
        "name":         "Light",
        "icon":         "☀️",
        "bg":           "#F5F5F5",
        "accent":       "#E0E0E0",
        "text":         "#1A1A1A",
        "subtext":      "#666666",
        "gold":         "#B8860B",
        "price":        "#3333AA",
        "divider":      "#BDBDBD",
        "back_bar":     "#ECECEC",
        "back_divider": "#D0D0D0",
        "up":           "#00A84F",
        "down":         "#D32F2F",
        "entry_fg":     "#1A1A1A",
    },
    "matrix": {
        "name":         "Green / Matrix",
        "icon":         "💚",
        "bg":           "#0D0D0D",
        "accent":       "#0A2A0A",
        "text":         "#00FF41",
        "subtext":      "#006600",
        "gold":         "#00FF41",
        "price":        "#39FF14",
        "divider":      "#004400",
        "back_bar":     "#050D05",
        "back_divider": "#003300",
        "up":           "#00FF41",
        "down":         "#FF4444",
        "entry_fg":     "#00FF41",
    },
}